graph TD
    subgraph Public_Internet
        P[Patient App]
        D[Doctor Portal]
    end
    subgraph DMZ
        WAF[API Gateway / WAF]
    end
    subgraph App_Layer
        Auth[Identity Svc]
        Appt[Appt Svc]
        PHI[Health Svc]
    end
    subgraph Data_Layer
        UDB[(User DB)]
        HDB[(Encrypted DB)]
        V[Vault]
    end
    P & D --> WAF
    WAF --> Auth & Appt & PHI
    Auth --> UDB
    PHI --> HDB
    Auth & PHI -.-> V
